### ISSUE TITLE
Window Scrolling when up/down key is pressed.

### ISSUE THREAD

**Issue by grapheo12** [soumyajit1729/TheSnakeGame#1]
When up or down key is pressed in-game, only the snake should move. Instead, the window also scrolls up/down which is default behaviour.

**Comment by soumyajit1729** [comment]
> When up or down key is pressed in-game, only the snake should move. Instead, the window also scrolls up/down which is the default behavior.

yes, I have made the page size small such that it can lie on the screen fully. now there is not any scroll bar
